SET SQL_MODE = `NO_AUTO_VALUE_ON_ZERO`;
START TRANSACTION;
SET time_zone = `+00:00`;

CREATE TABLE `student_data` (
  `Initial` varchar(5) NOT NULL,
  `Name` varchar(30) NOT NULL,
  `Course` varchar(30) NOT NULL,
  `Department` varchar(30) NOT NULL,
  `Batch` varchar(10) NOT NULL,
  `Roll_No` int(10) NOT NULL,
  `A_U_NO` varchar(20) NULL,
  `Section` varchar(5) NOT NULL,
  `Gender` varchar(10) NOT NULL,
  `Food` varchar(10) NOT NULL,
  `Blood_Group` varchar(10) NOT NULL,
  `Aadhaar_No`  int(12) NOT NULL,
  `Student_MailID` varchar(50) NOT NULL,
  `Date_of_Birth` varchar(15) NOT NULL,
  `Caste` varchar(30) NOT NULL,
  `Community` varchar(10) NOT NULL,
  `Community_Others` varchar(40) NULL,
  `Parent_Annual_Income` varchar(10) NOT NULL,
  `Religion` varchar(40) NOT NULL,
  `Nationality` varchar(40) NOT NULL,
  `Mother_Tongue` varchar(40) NOT NULL,
  `Member_Of` varchar(10) NOT NUll,
  `Date_Of_Admission` varchar(15) NOT NULL,
  `Admission_Allotment` varchar(20) NOT NULL,
  `Sports_Admission1` varchar(40) NULL,
  `Sports_Admission2` varchar(40) NULL,
  `Overall_Rank` varchar(10) NOT NULL,
  `Community_Rank` varchar(10) NOT NULL,
  `Sports_Admission3` varchar(40) NOT NULL,
  `Game_Name` varchar(40) NULL,
  `Medium_Of_Instruction` varchar(40) NOT NULL,
  `Medium_Of_Instruction_Others` varchar(40) NULL,
  `Country_Name` varchar(40) NULL,
`passport_number` varchar(40) NULL,
`passport_expiry` varchar(40) NULL,
`visa_number` varchar(40) NULL,
`type_of_visa` varchar(40) NULL,
`visa_expiry` varchar(40) NULL,
`tenth_school` varchar(40) NOT NULL,
`tenth_board` varchar(40) NOT NULL,
`tenth_reg` varchar(40) NOT NULL,
`tenth_yearofpassing` varchar(40) NOT NULL,
`tenth_markpercent` varchar(40) NOT NULL,
`twelveth_school` varchar(40) NOT NULL,
`twelveth_board` varchar(40) NOT NULL,
`twelveth_reg` varchar(40) NOT NULL,
`twelveth_yearofpassing` varchar(40) NOT NULL,
`twelveth_markpercent` varchar(40) NOT NULL,
`max_mathmarks` varchar(40) NOT NULL,
`obtained_mathmarks` varchar(40) NOT NULL,
`percent_mathmarks` varchar(40) NOT NULL,
`max_physicsmarks` varchar(40) NOT NULL,
`obtained_physicsmarks` varchar(40) NOT NULL,
`percent_physicsmarks` varchar(40) NOT NULL,
`max_chemistrymarks` varchar(40) NOT NULL,
`obtained_chemistrymarks` varchar(40) NOT NULL,
`percent_chemistrymarks` varchar(40) NOT NULL,
`max_totalmarks` varchar(40) NOT NULL,
`obtained_totalmarks` varchar(40) NOT NULL,
`percent_totalmarks`  varchar(40) NOT NULL,
`father_name` varchar(40) NOT NULL,
`mother_name` varchar(40) NOT NULL,
`father_qualification` varchar(40) NOT NULL,
`mother_qualification` varchar(40) NOT NULL,
`father_occupation` varchar(40) NULL,
`mother_occupation` varchar(40) NULL,
`father_addressofcompany` varchar(40) NULL,
`mother_addressofcompany` varchar(40) NULL,
`father_designation` varchar(40) NULL,
`mother_designation` varchar(40) NULL,
`father_mail` varchar(40) NULL,
`mother_mail` varchar(40) NULL,
`father_countrycode` varchar(40) NULL,
`mother_countrycode` varchar(40) NULL,
`father_stdcode` varchar(40) NULL,
`mother_stdcode` varchar(40) NULL,
`father_landline` varchar(40) NULL,
`mother_landline` varchar(40) NULL,
`father_moblie` varchar(40) NULL,
`mother_mobile` varchar(40) NULL,
`residence_doorno` varchar(40) NOT NULL,
`permanent_doorno` varchar(40) NOT NULL,
`residence_streetname` varchar(40) NOT NULL,
`permanent_streetname` varchar(40) NOT NULL,
`residence_area` varchar(40) NOT NULL,
`permanent_area` varchar(40) NOT NULL,
`residence_city` varchar(40) NOT NULL,
`permanent_city` varchar(40) NOT NULL,
`residence_district` varchar(40) NOT NULL,
`permanent_district` varchar(40) NOT NULL,
`residence_country` varchar(40) NOT NULL,
`permanent_country` varchar(40) NOT NULL,
`residence_state` varchar(40) NOT NULL,
`permanent_state` varchar(40) NOT NULL,
`residence_pincode` varchar(40) NOT NULL,
`permanent_pincode` varchar(40) NOT NULL,
`dayscholar_area` varchar(40) NOT NULL,
`dayscholar_boardingpoint` varchar(40) NOT NULL,
`guardian1_name` varchar(40) NOT NULL,
`guardian2_name` varchar(40) NOT NULL,
`guardian1_occupation` varchar(40) NULL,
`guardian2_occupation` varchar(40) NULL,
`guardian1_age` varchar(40) NOT NULL,
`guardian2_age` varchar(40) NOT NULL,
`guardian1_dob` varchar(40) NOT NULL,
`guardian2_dob` varchar(40) NOT NULL,
`guardian1_landline` varchar(40) NULL,
`guardian2_landline` varchar(40) NULL,
`guardian1_mobile` varchar(40) NOT NULL,
`guardian2_mobile` varchar(40) NOT NULL,
`guardian1_homeaddress` varchar(80) NOT NULL,
`guardian2_homeaddress` varchar(80) NOT NULL,
`guardian1_officeaddress` varchar(80) NULL,
`guardian2_officeaddress` varchar(80) NULL,
`student_photo` longblob NOT NULL,
`father_photo` longblob NOT NULL,
`mother_photo` longblob NOT NULL,
`aadhaar_photo` longblob NOT NULL,
`community_certificate` longblob NOT NULL,
`tenth_certificate` longblob NOT NULL,
`twelveth_certificate` longblob NOT NULL


  )  ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED;


CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;