SET SQL_MODE = `NO_AUTO_VALUE_ON_ZERO`;
START TRANSACTION;
SET time_zone = `+00:00`;

CREATE TABLE `information` (
  `clginfo` varchar(30) NOT NULL,
  `name` varchar(5) NOT NULL,
  `initial` varchar(30) NOT NULL,
  `section` varchar(30) NOT NULL,
  `gender` varchar(30) NOT NULL,
  `course` varchar(10) NOT NULL,
  `food` int(10) NOT NULL,
  `department` varchar(5) NOT NULL,
  `blood` varchar(10) NOT NULL,
  `batch` varchar(10) NOT NULL,
  `aadharno`  int(12) NOT NULL,
  `rollno` varchar(10) NOT NULL,
  `phno` varchar(50) NOT NULL,
  `email` varchar(15) NOT NULL,
  `dob` varchar(15) NOT NULL,
  `caste` varchar(10) NOT NULL,
  `community` varchar(40) NULL,
  `parentinan` varchar(10) NOT NULL,
  `religion` varchar(40) NOT NULL,
  `nationality` varchar(40) NOT NULL,
  `tongue` varchar(40) NOT NULL,
  `membersof` varchar(10) NOT NUll,
  `doa` varchar(15) NOT NULL,
  `adminall` varchar(20) NOT NULL,
  `adtype` varchar(40) NULL,
  `admincat` varchar(40) NULL,
  `overallrank` varchar(10) NOT NULL,
  `communityrank` varchar(10) NOT NULL,
  `sportsadmin` varchar(40) NOT NULL,
  `specifygame` varchar(40) NULL,
  `medium` varchar(40) NOT NULL,
  `nriorfor` varchar(40) NULL,
`passnumber` varchar(40) NULL,
`passexpiry` varchar(40) NULL,
`visanum` varchar(40) NULL,
`visatype` varchar(40) NULL,
`visaexpiry` varchar(40) NULL,
`tenschorclg` varchar(40) NOT NULL,
`tenboard` varchar(40) NOT NULL,
`tenreg` varchar(40) NOT NULL,
`tendeg` varchar(40) NOT NULL,
`tenspecial` varchar(40) NOT NULL,
`tenpass` varchar(40) NOT NULL,
`tenmark` varchar(40) NOT NULL,
`tenclass` varchar(40) NOT NULL,
`tengrade` varchar(40) NOT NULL,
`tweschorclg` varchar(40) NOT NULL,
`tweboard` varchar(40) NOT NULL,
`twereg` varchar(40) NOT NULL,
`twedeg` varchar(40) NOT NULL,
`twespecial` varchar(40) NOT NULL,
`twepass` varchar(40) NOT NULL,
`twemark` varchar(40) NOT NULL,
`tweclass` varchar(40) NOT NULL,
`twegrade` varchar(40) NOT NULL,
`dipschorclg` varchar(40) NOT NULL,
`dipboard` varchar(40) NOT NULL,
`dipreg` varchar(40) NOT NULL,
`dipdeg` varchar(40) NOT NULL,
`dipspecial` varchar(40) NOT NULL,
`dippass` varchar(40) NOT NULL,
`dipmark` varchar(40) NOT NULL,
`dipclass` varchar(40) NOT NULL,
`dipgrade` varchar(40) NOT NULL,
`ugschorclg` varchar(40) NOT NULL,
`ugboard` varchar(40) NOT NULL,
`ugreg` varchar(40) NOT NULL,
`ugdeg` varchar(40) NOT NULL,
`ugspecial` varchar(40) NOT NULL,
`ugpass` varchar(40) NOT NULL,
`ugmark` varchar(40) NOT NULL,
`ugclass` varchar(40) NOT NULL,
`uggrade` varchar(40) NOT NULL,
`pgschorclg` varchar(40) NOT NULL,
`pgboard` varchar(40) NOT NULL,
`pgreg` varchar(40) NOT NULL,
`pgdeg` varchar(40) NOT NULL,
`pgspecial` varchar(40) NOT NULL,
`pgpass` varchar(40) NOT NULL,
`pgmark` varchar(40) NOT NULL,
`pgclass` varchar(40) NOT NULL,
`pggrade` varchar(40) NOT NULL,


`mathmax` varchar(40) NOT NULL,
`mathob` varchar(40) NOT NULL,
`mathper` varchar(40) NOT NULL,
`phymax` varchar(40) NOT NULL,
`phyob` varchar(40) NOT NULL,
`phyper` varchar(40) NOT NULL,
`chemmax` varchar(40) NOT NULL,
`chemob` varchar(40) NOT NULL,
`chemper` varchar(40) NOT NULL,
`totmax` varchar(40) NOT NULL,
`totob` varchar(40) NOT NULL,
`totper`  varchar(40) NOT NULL,
`fathername` varchar(40) NOT NULL,
`mothername` varchar(40) NOT NULL,
`fatherqual` varchar(40) NOT NULL,
`motherqual` varchar(40) NOT NULL,
`fatherocc` varchar(40) NULL,
`motherocc` varchar(40) NULL,
`fatheraddcom` varchar(40) NULL,
`motheraddcom` varchar(40) NULL,
`fatherdis` varchar(40) NULL,
`motherdis` varchar(40) NULL,
`fathermail` varchar(40) NULL,
`mothermail` varchar(40) NULL,
`fathercouncode` varchar(40) NULL,
`mothercouncode` varchar(40) NULL,
`fatherstd` varchar(40) NULL,
`motherstd` varchar(40) NULL,
`fatherlln` varchar(40) NULL,
`motherlln` varchar(40) NULL,
`fathermn` varchar(40) NULL,
`mothermn` varchar(40) NULL,
`resplot` varchar(40) NOT NULL,
`perplot` varchar(40) NOT NULL,
`resstreet` varchar(40) NOT NULL,
`perstreet` varchar(40) NOT NULL,
`resarea` varchar(40) NOT NULL,
`perarea` varchar(40) NOT NULL,
`rescity` varchar(40) NOT NULL,
`percity` varchar(40) NOT NULL,
`resdistrict` varchar(40) NOT NULL,
`perdistrict` varchar(40) NOT NULL,
`rescoun` varchar(40) NOT NULL,
`percoun` varchar(40) NOT NULL,
`resstate` varchar(40) NOT NULL,
`perstate` varchar(40) NOT NULL,
`respin` varchar(40) NOT NULL,
`perpin` varchar(40) NOT NULL,
`areaorbus` varchar(40) NOT NULL,
`bp` varchar(40) NOT NULL,
`gua1name` varchar(40) NOT NULL,
`gua2name` varchar(40) NOT NULL,
`gua1pro` varchar(40) NULL,
`gua2pro` varchar(40) NULL,
`gua1age` varchar(40) NOT NULL,
`gua2age` varchar(40) NOT NULL,
`gua1lln` varchar(40) NULL,
`gua2lln` varchar(40) NULL,
`gua1mn` varchar(40) NOT NULL,
`gua2mn` varchar(40) NOT NULL,
`gua1addho` varchar(80) NOT NULL,
`gua2addho` varchar(80) NOT NULL,
`gua1addof` varchar(80) NULL,
`gua2addof` varchar(80) NULL,
`studentphoto` varchar(250) NOT NULL,
`fatherphoto` varchar(250) NOT NULL,
`motherphoto` varchar(250) NOT NULL,
`aadharphoto` varchar(250) NOT NULL,
`communitycert` varchar(250) NOT NULL,
`tenthcert` varchar(250) NOT NULL,
`twelcert` varchar(250) NOT NULL,
`allorder` varchar(250) NOT NULL,
`passportphoto` varchar(250) NOT NULL


  )  ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED;

